- tests/test_part_image.py
- tests/test_rootfs.py
Aim of this repository is to hold test scripts which
can be shared between two other repositories, i.e.
mendersoftware/meta-mender & mendersoftware/mender-conversion-tools.
The character of separately kept scripts allows to
use them for testing of both types of Mender images:
- automated Yocto built images
- non-Yocto images built manually with mender-conversion-tools
Issues: MEN-2099
Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>
> Add basic tests which verify Mender image correctness

- tests/test_part_image.py
Issues: MEN-2241
Signed-off-by: Adam Podogrocki <a.podogrocki@gmail.com>
> Fix setting env_uboot_size for testing RPI3 partition alignment

- tests/test_rootfs.py
> MEN-2290: Verify that rootfs data directory is empty.

- tests/test_part_image.py
Since mender-convert v2, the test seems to pass. Adjust pytest
expectation accordingly.
> Expect PASS on equal checksum tests for mender-convert run

- tests/test_part_image.py
- tests/test_rootfs.py
Update all the acceptance tests to the Python3 and Fabric2.
Changelog: Upgrading tests to Python3 and Fabric2.
Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>
> upgrade image tests to Python3

- tests/test_part_image.py
Clears up warning `DeprecationWarning: invalid escape sequence \s`
> Properly escape special characters in regular expression

- tests/test_part_image.py
- tests/test_update.py
The actual code changes are:
* [test_update] Increase size of "too big" image to 4GiB
As mender-convert images have rootfs partitions bigger than 1GiB.
* [test_update] Handle images with no transient mender.conf
As happens to be the case for mender-convert images.
The test can be executed the same way, only needs to be taken into
account in the preparation and clean-up.
> MEN-2208: test_update.py to mender-image-tests

- tests/test_update.py
The bugfix is not available for earlier versions of the client.
> test_standalone_update_rollback: Set to min mender 2.3.1

- tests/test_part_image.py
- tests/test_rootfs.py
- tests/test_update.py
To align with acceptance tests in:
https://github.com/mendersoftware/meta-mender/pull/1158
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> rename: min_mender_version -> min_mender_client_version

- tests/utils/fixtures/fixtures.py
* [fixtures.py] Port connection/second_connection fixtures
From https://github.com/mendersoftware/meta-mender/commit/49b68826f75d150f2d176a54598d571260fd7012
* [fixtures.py] Port not_for_machine fixture
From https://github.com/mendersoftware/meta-mender/commit/52aaae10d907b494c0dfcc4cbae40f401b7d5971
> Port framework improvements from meta-mender/feature branch

- tests/utils/parseropts/parseropts.py
Ref:
https://northern-tech.slack.com/archives/C2D3HRU9M/p1607442874010000?thread_ts=1607441097.005200&cid=C2D3HRU9M
> Register the missing 'not_for_machine' pytest marker

- tests/test_update.py
The second part of this test, which zeroes the environment and expects
fw_printenv to fail, fails on zeus (and older, if run) due to the
using u-boot-fw-utils which has a default environment.
> [test_update] Mark test_uboot_mender_saveenv_canary for dunfell

- tests/test_part_image.py
- tests/utils/parseropts/parseropts.py
It seems to have been introduced by mistake during the Python3 upgrade
in November 2019.
Before this refactoring, there was no marker nor logic to skip any test
based on this; it was only used inside fixtures or specific tests to
modify their behaviour (for example, to decide on the path where the
image under test is expected to be).
See:
* https://github.com/mendersoftware/mender-image-tests/commit/a6cfbd1b09412784dcdd0dabaa67662129a8ff87
* https://github.com/mendersoftware/meta-mender/commit/a12742dc4aceeb6e560242590c5f42ce4c3868cc
Also, generally speaking, any test that is in this submodule is expected
to be run both on mender-convert and meta-mender (some configuration
exceptions may apply to the latter), but in any case a "conversion only"
test would need to live in mender-convert …
> Remove "conversion" marker and logic to skip tests based on this

- tests/test_rootfs.py
- tests/utils/fixtures/fixtures.py
- tests/utils/parseropts/parseropts.py
And a corresponding fixture to skip tests (like this one) that are not
applicable for a given feature (mender-convert in this case).
> test_rootfs: Add test for mender-shell installation

- tests/test_rootfs.py
Update test to expect User field too in the config file.
In addition:
* test_expected_files_ext234_mender_shell: Rework to verify mender-convert
Verify that the files exist when expected (yocto integration) and that
they are not there when not expected (mender-convert), instead of just
skipping for the latter.
Which addresses https://github.com/mendersoftware/mender-image-tests/pull/33#discussion_r542224113
> test_expected_files_ext234_mender_shell: Update test

- tests/utils/fixtures/fixtures.py
> Move build definition to meta-mender build files instead of scripts.

- tests/test_rootfs.py
meta-mender-demo sets the mender-connect shell to /bin/bash; update the
tests to match this new setting.
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio@tranchitella.eu>
> Update tests to match the latest meta-mender

- tests/test_part_image.py
- tests/test_rootfs.py
This file won't be present in some mender-convert images from now on.
And having plans to remove the file all together soon, it makes no sense
complicating the test logic to make this check conditional.
Plus couple of misc fixes:
* test_device_type: fix typo
* test_equal_checksum_part_image_and_artifact: support uncompressed
Support extracting an uncompressed file system from the Artifact.
> MEN-4256: test_rootfs.py: Remove checks for artifact_info file (+ misc)

- tests/test_rootfs.py
Signed-off-by: Lluis Campos <lluis.campos@northern.tech>
(cherry picked from commit 04b5047a316aa5757ee8c0b89174bf71ee9fd73d)
Cherry-picked to an earlier side branch so that we can get this change
into dunfell without the rest of the changes in master.
> [test_expected_files_ext234_mender_connect] Remove ServerURL

- tests/utils/fixtures/fixtures.py
Following changes from integration test framework. See:
* https://github.com/mendersoftware/integration/pull/1333
* https://github.com/mendersoftware/integration/pull/1336
> paramiko: set look_for_keys and allow_agent to False

- tests/test_update_modules.py
As the rollback functionality requires a non-released bug fix.
> test_single_file_update_module: Set min version to 2.7.0

- tests/test_rootfs.py
So that the test can be skip for images containing no client (like the
pre-built images from mender-convert).
> test_expected_files_ext234: only with feature "mender-client-install"

- tests/utils/common/common.py
- tests/utils/fixtures/fixtures.py
- tests/utils/parseropts/parseropts.py
It is extremely unlikely that we will use these in a new HW farm.
Follow-up from https://github.com/mendersoftware/meta-mender/pull/1395
Also, set the default for --board-type to a valid QEMU board...
> Remove unused hardware setup functions

- tests/test_rootfs.py
Only applicable for mender-convert images, yocto ones have an explicit
test for the add-on.
> New test test_expected_files_ext234_mender_monitor

- tests/test_secure_boot.py
- tests/test_update.py
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
> test: add missing sentinel 'uefiimg' to the secure-boot test

- tests/utils/fixtures/fixtures.py
This way we avoid having to deal with the new ":" syntax, which may
become a problem if we import the repo to an old meta-mender branch.
> chore: Move IMAGE_FEATURES setting to meta-mender.

- tests/utils/common/common.py
New versions of the scp program uses the SFTP protocol by
default. However SFTP is not installed in our qemu hosts, and hence
this does not work.
The fix is simple. Fall back to the legacy functionality. The SCP
protocol, though aged, works just fine for our needs.
> ci(scp): Fall back to the legacy SCP protocol

- tests/test_update.py
- tests/utils/common/common.py
- tests/utils/fixtures/fixtures.py
```
We are using an extremely small subset of Fabric's features, which is
easily replicated with a small class calling ssh. The upside is that
it is much more compatible, and the `--capture` option does not need
to be set to `--capture=no` anymore. This is great for several
reasons:
* xdist doesn't support this mode.
* We can get per-test log output by using different `--capture`
options (such as the default `--capture=fd`).
* The console isn't flooded with messages anymore.
* Only the log from failing tests is printed by default.
There is one downside, but this is possible to improve later: Output
is not printed while the command is running anymore, but only after it
has finished. This only has a practical effect if going back to the
`--capture=no` mode though, since the other modes …
```
> test: Fix `--capture` option by removing Fabric.

- tests/test_rootfs.py
> test: Test that artifact_info exists alongside the right client versions.

- tests/utils/common/common.py
TCP keep-alives are enabled by default on SSH connections, but it doesn't help because the connection is terminated at the QEMU process, which is fine. QEMU has then proxied the connection inside its VM to the ssh server, but this is a separate connection, which never times out, and which we have no control over.
Luckily, SSH has a protocol keep-alive mechanism as well, which is end-to-end, it's just not enabled by default.
Keeping this interval very long in order to deal with slow CI runners is probably not necessary, because there is no payload traffic going over it, so it should not be affected by load.
> test: Time out properly when ssh server on device dies.

- tests/utils/common/common.py
* chore(common.py): Remove unused imports
*  chore(common.py): Migrate from deprecated distutils
Clears `DeprecationWarning`. See:
https://peps.python.org/pep-0632/#migration-advice
> chore(common.py): Migrate from deprecated distutils

- tests/utils/common/common.py
This simply accepts a connection to a running QEMU host adn returns the local system time using the date command.
Ticket: QA-483
> feat: Add the qemu_system_time function

- tests/test_part_image.py
- tests/test_rootfs.py
- tests/test_update.py
- tests/test_update_modules.py
- tests/utils/fixtures/fixtures.py
- tests/utils/parseropts/parseropts.py
Use a marker and two command line options to mark and select/deselect
tests that are platform agnostic.
The default behavior will be the same (aka run all tests), while the
user  can optionally skipping the platform agnostic tests or run them
exclusively.
Mark then all tests accordingly. Along the way, minor tests doc
improvements have been made.
> QA-487: feat: Split out cross-platform tests

- tests/utils/common/common.py
This should have broken years ago, and it is unknown why this has worked earlier. Possibly the version library in Python has become stricter when parsing letters.
> test: Detect minimum version correctly for N.M.x style branches.

- tests/utils/common/common.py
Otherwise `packaging.version.Version` will through `InvalidVersion` and the helper will assume a "master" kind of version.
> test: Properly handle build tags in `version_is_minimum`

- tests/test_rootfs.py
- tests/test_update.py
- tests/utils/common/common.py
- tests/utils/fixtures/fixtures.py
Using a different helper to document in code (and only once) why we need
this unintuitive change.
Merge the `mender-flash` test with the main client files test so that we
can reuse also the new helper. The main test was already differentiating
from golang to C++ anyway.
> test: Set minimum version for C++ related handling to `3.6.0`

- tests/test_rootfs.py
Both conditions can be true; if Mender is installed, then the file
will be there, if it's not installed, then it won't. We don't track
this condition in the tests currently.
Since we now run package scripts, it's better to test this condition
in mender-dist-packages anyway, so just remove it from here.
> test: Remove test for mender.conf, which is less relevant now. 

- tests/test_update.py
If the daemon is stopped, systemctl will return 3.
> Don't check return value  in standalone test

- tests/utils/fixtures/fixtures.py
Adds session-scoped connection fixture with autouse so the fixture can be used in session finish hook.
Ticket: QA-1099
> feat: add connection fixture session scope copy

- tests/utils/fixtures/fixtures.py
- adds a step right before the QEMU VM ran by tests is powered off to attempt to retrieve journal logs from the VM
- places the logs under `/tmp` so they can be picked up as job artifacts by the CI (TODO: add link to the PR with CI changes)
Ticket: QA-1099
> test: archive journal logs from live QEMU VM
