mendersoftware/mender-image-tests

tests/test_part_image.py
=> Add test for MEN-2145.

tests/test_part_image.py
=> Require minimum Yocto version for test_split_mender_conf test.

tests/test_part_image.py
=> Add test to verify that artifact and part image checksums are equal.

tests/test_part_image.py, tests/test_rootfs.py
Some minor beatifications. See individual commits.
=> QA-120: Acceptance tests python3 for mender-convert

tests/test_part_image.py, tests/test_rootfs.py, tests/test_update.py
=> Follow meta-mender: Change DISTRO_FEATURES to MENDER_FEATURES.

tests/utils/common/common.py
Porting https://github.com/mendersoftware/meta-mender/commit/c4bffbd80b86e20bfd9592432d3b997ae83a1b3b
=> Simplify get_bitbake_variables by doing env calculation inside it

tests/test_update.py
=> Add one missing check for the legacy DISTRO_FEATURES variable.

tests/test_rootfs.py
Changelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
=> MEN-4292: Rename mender-shell to mender-connect

tests/test_part_image.py, tests/test_rootfs.py
Changeelog: none
Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
=> Adjust acceptance tests to the latest mender-convert

tests/utils/common/common.py
Taken from:
https://github.com/mendersoftware/meta-mender/blob/e180c9269e66d703c7eaec3374c751d35661652e/tests/acceptance/test_dbus.py#L25
=> common.py: New method cleanup_mender_state

tests/utils/common/common.py, tests/utils/fixtures/fixtures.py, tests/utils/parseropts/parseropts.py
Might come-in handy when debugging tests :)
=> New command line argument to keep temporary build dir

tests/test_update.py, tests/utils/common/common.py
=> Adapt to the new grub-mender-grubenv-* tools.

tests/utils/fixtures/fixtures.py
Grab the coverage files after each test instead of once at the end.
=> Fix failures in long test runs because coverage fills up data part.

tests/test_update.py
=> Make grub-mender-grubenv location adjustment for BIOS as well.

tests/utils/fixtures/fixtures.py, tests/utils/parseropts/parseropts.py
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>
=> Prepare the tests for real hardware

tests/test_secure_boot.py
=> test: Invert Secure Boot pass condition when grub.d integ. is off.

tests/utils/helpers/helpers.py
Instead of an arbitrary hard-coded 1 second sleep, use redo package to retry for five times.
=> chore(helpers.py): Retry HTTP server start-up check

tests/test_update.py, tests/utils/fixtures/fixtures.py
=> test: Move skip condition earlier so we don't hit the worker check.

tests/utils/common/common.py
Upstream has changed the (internal) variables so we need to adapt our workaround for the race condition.
=> chore: Update `ReadFileLock` code for latest `filelock` release

tests/test_rootfs.py
=> test: Test that `/data` mountpoint exists in rootfs.

tests/utils/fixtures/fixtures.py
As far as I can tell, this fixture is not in use. Fixing it for the sake of consistency and future proofing :)
=> test: Add handling of old features variable to fixture

tests/test_update.py
=> test: rootfs-image: Add test for rolling back after committing.

tests/test_update.py
See bug fix at:
* https://github.com/mendersoftware/mender/pull/1705
=> MEN-7818: Add explicit test updating from standalone state v1

tests/test_update.py
The tests running on qemux86_64 in mender-convert failed because the database wasn't updated while mender-update was running - restarting the daemon fixed it.
See https://gitlab.com/Northern.tech/Mender/mender-convert/-/pipelines/1620218352 for a pipeline using this fix
=> test: stop mender-update daemon before updating database 
